### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Innei** [vortesnail/qier-progress#1]
![image](https://user-images.githubusercontent.com/41265413/74532470-3acf1900-4f6a-11ea-9475-0e7154c050a7.png)

**Comment by vortesnail** [comment]
How cause it？ a code print could be better

**Comment by Innei** [comment]
Sorry, it cause by my code which wrote long time ago in router. But crashed when my add your lib. So it my fault.

By the way, can you remove debug code in this lib? such as console.log

**Comment by vortesnail** [comment]
> Sorry, it cause by my code which wrote long time ago in router. But crashed when my add your lib. So it my fault.
> 
> By the way, can you remove debug code in this lib? such as console.log

Aha, sorry for that, i ll fix it.
